name: PR checks
on:
  pull_request:

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: flake8 Lint
        uses: reviewdog/action-flake8@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          flake8_args: --config=.flake8 gulfstream
          reporter: github-pr-review
          fail_on_error: true
          
  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install bandit
        run: pip3 install bandit==1.6.2
      - name: bandit Lint
        run: bandit -r . -s B101 -o "security_report.txt" -f 'txt'
      - name: Security check report artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: Bandit report
          path: security_report.txt
